project/stocks/__init__.py
"""
The stocks blueprint handles the user management for this application.
Specifically, this blueprint allows for users to add, edit, and delete
stock data from their portfolio.
"""
from flask import Blueprint

stocks_blueprint = Blueprint('stocks', __name__, template_folder='templates')

from . import routes

project/stocks/routes.py
#################
#### imports ####
#################
from . import stocks_blueprint
from flask import render_template, request, redirect, url_for, flash, current_app, abort
from flask_login import login_required, current_user
from project.models import Stock
from project import database
from datetime import datetime
import click


###########################
#### request callbacks ####
###########################

# @stocks_blueprint.before_request
# def stocks_before_request():
#     current_app.logger.info('Calling before_request() for the stocks blueprint...')
#
#
# @stocks_blueprint.after_request
# def stocks_after_request(response):
#     current_app.logger.info('Calling after_request() for the stocks blueprint...')
#     return response
#
#
# @stocks_blueprint.teardown_request
# def stocks_teardown_request(error=None):
#     current_app.logger.info('Calling teardown_request() for the stocks blueprint...')


######################
#### cli commands ####
######################

@stocks_blueprint.cli.command('create_default_set')
def create_default_set():
    """Create three new stocks and add them to the database"""
    stock1 = Stock('HD', '25', '247.29')
    stock2 = Stock('TWTR', '230', '31.89')
    stock3 = Stock('DIS', '65', '118.77')
    database.session.add(stock1)
    database.session.add(stock2)
    database.session.add(stock3)
    database.session.commit()


@stocks_blueprint.cli.command('create')
@click.argument('symbol')
@click.argument('number_of_shares')
@click.argument('purchase_price')
def create(symbol, number_of_shares, purchase_price):
    """Create a new stock and add it to the database"""
    stock = Stock(symbol, number_of_shares, purchase_price)
    database.session.add(stock)
    database.session.commit()


################
#### routes ####
################

@stocks_blueprint.route('/')
def index():
    current_app.logger.info('Calling the index() function.')
    return render_template('stocks/index.html')


@stocks_blueprint.route('/add_stock', methods=['GET', 'POST'])
@login_required
def add_stock():
    if request.method == 'POST':
        # Save the form data to the database
        if current_user.has_funds(request.form['purchase_price'], request.form['number_of_shares']):
            new_stock = Stock(request.form['stock_symbol'],
                        request.form['number_of_shares'],
                        request.form['purchase_price'],
                        current_user.id,
                        datetime.fromisoformat(request.form['purchase_date']))
            database.session.add(new_stock)
            database.session.commit()

            current_user.subtract_funds(request.form['purchase_price'], request.form['number_of_shares'])
            database.session.add(current_user)
            database.session.commit()

            flash(f"Added new stock ({ request.form['stock_symbol'] })!", 'success')
            current_app.logger.info(f"Added new stock ({ request.form['stock_symbol'] })!")
            return redirect(url_for('stocks.list_stocks'))
        else:
            flash(f"Not Enough Funds To Add Stock!", 'error')
            current_app.logger.info(f"Not Enough Funds To Add Stock!")
            return render_template('stocks/add_stock.html')
    else:
        return render_template('stocks/add_stock.html')


@stocks_blueprint.route('/stocks', methods=['GET', 'POST'])
@login_required
def list_stocks():
    if request.method == 'POST':
        # Get stock to sell
        to_sell = Stock.query.get(int(request.form['sell_stock_id']))
        # Update user funds
        current_user.add_funds(to_sell.current_price / 100, to_sell.number_of_shares)
        database.session.add(current_user)
        database.session.commit()
        # Clear stock
        to_sell.number_of_shares = 0
        database.session.add(to_sell)
        database.session.commit()

        return redirect(url_for('stocks.list_stocks'))
    else:
        stocks = Stock.query.order_by(Stock.id).filter_by(user_id=current_user.id).all()

        current_account_value = 0.0
        for stock in stocks:
            stock.get_stock_data()
            database.session.add(stock)
            if stock.number_of_shares > 0:
                current_account_value += stock.get_stock_position_value()
        database.session.commit()
        return render_template('stocks/stocks.html', stocks=stocks, value=round(current_account_value, 2))


@stocks_blueprint.route('/stocks/<id>')
@login_required
def stock_details(id):
    stock = Stock.query.filter_by(id=id).first_or_404()

    if stock.user_id != current_user.id:
        abort(403)

    title, labels, values = stock.get_weekly_stock_data()
    return render_template('stocks/stock_details.html', stock=stock, title=title, labels=labels, values=values)

project/stocks/templates/stocks/add_stock.html
{% extends "base.html" %}

{% block styling %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/add_stock_style.css') }}">
{% endblock %}

{% block content %}
<h2 class="add-stock-heading">Add a Stock:</h2>
<div>
  <h3>Your current funds: {{ current_user.current_funds / 100 }}</h3>
</div>
<form method="post">
  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>

  <label for="stockSymbol">Stock Symbol (<i>required</i>):</label>
  <input type="text" id="stockSymbol" name="stock_symbol" required pattern="[A-Z]{1,5}" />
  <br>
  <label for="numberOfShares">Number of Shares (<i>required</i>):</label>
  <input type="text" id="numberOfShares" name="number_of_shares" required />
  <br>
  <label for="purchasePrice">Purchase Price (<i>required</i>) ($):</label>
  <input type="text" id="purchasePrice" name="purchase_price" required />
  <br>
  <label for="purchaseDate">Purchase Date (<i>required</i>):</label>
  <input type="date" id="purchaseDate" name="purchase_date" placeholder="YYYY-MM-DD" required />
  <br>
  <input type="submit">
</form>
{% endblock %}

project/stocks/templates/stocks/index.html
{% extends "base.html" %}

{% block styling %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/index_style.css') }}">
{% endblock %}

{% block content %}
<div class="container">
  <div class="content-text">
    <h2>Welcome to the Stock Portfolio Management App!</h2>
    <p>Monitor your stock portfolio value</p>
    <p>and view historical stock data.</p>
  </div>
  <div class="content-image">
    <img src="{{ url_for('static', filename='img/stock_chart.jpg') }}" alt="stock_chart">
  </div>
</div>
{% endblock %}

project/stocks/templates/stocks/stock_details.html
{% extends "base.html" %}

{% block styling %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/stocks_style.css') }}">
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
{% endblock %}

{% block content %}
<h2>Stock Details:</h2>
<br>
<h3>Symbol: {{ stock.stock_symbol }}</h3>
<h3>Number of Shares: {{ stock.number_of_shares }}</h3>
<h3>Purchase Price: ${{ stock.purchase_price / 100 }}</h3>
<h3>Purchase Date: {{ stock.purchase_date.strftime("%B %d, %Y") }}</h3>
<br>

{% if title %}
  <canvas id="stockChart" width="500" height="400"></canvas>
{% endif %}
{% endblock %}

{% block javascript %}
<script>
// Get the canvas element for modifying the data contents
var ctx = document.getElementById('stockChart').getContext('2d');

// Set the default font color for each chart
Chart.defaults.global.defaultFontColor = 'white';

// Create a new line chart
var myChart = new Chart(ctx, {
  type: 'line',
  data: {
    labels:
      [{% for item in labels %}
         "{{item.strftime("%m/%d/%Y")}}",
      {% endfor %}],
    datasets: [{
      label: 'Share Price ($)',
      data:
        [{% for item in values %}
          {{item}},
        {% endfor %}],
    backgroundColor: 'blue',
    borderColor: 'white',
      borderWidth: 1
    }]
  },
  options: {
    title: {
      display: true,
      text: "{{ title }}"
    },
    legend: {
      display: true,
      position: 'bottom',
      align: 'center'
    },
    scales: {
      yAxes: [{
        ticks: {
          beginAtZero: true
        },
        gridLines:{
          color: "white",
        }
      }],
      xAxes: [{
        gridLines:{
          color: "white",
        }
      }]
    }
  }
});
</script>
{% endblock %}

project/stocks/templates/stocks/stocks.html
{% extends "base.html" %}

{% block styling %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/stocks_style.css') }}">
{% endblock %}

{% block content %}
<h2>List of Stocks:</h2>
<br>
<h3>Current Funds: {{ current_user.current_funds / 100 }}</h3>

<table id="stock-table">
  <!-- Table Header Row -->
  <tr>
    <th>Stock Symbol</th>
    <th>Number of Shares</th>
    <th>Purchase Price</th>
    <th>Purchase Date</th>
    <th>Current Share Price</th>
    <th>Stock Position Value</th>
    <th>Sell Shares</th>
  </tr>

  <!-- Table Elements (Rows) -->
  {% for stock in stocks %}
    {% if stock.number_of_shares > 0 %}
      <tr>
        <td><a href="{{ url_for('stocks.stock_details', id=stock.id) }}">{{ stock.stock_symbol }}</a></td>
        <td>{{ stock.number_of_shares }}</td>
        <td>${{ stock.purchase_price / 100 }}</td>
        <td>{{ stock.purchase_date.strftime("%Y-%m-%d") }}</td>
        <td>${{ stock.current_price / 100}}</td>
        <td>${{ stock.position_value / 100 }}</td>
        <td>
          <form class="sell_stock_form" method="post">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <input type="hidden" name="sell_stock_id" value="{{ stock.id }}"/>
            <input type="submit" name="sell_stock_submit" value="Sell">
          </form>
        </td>
      </tr>
    {% endif %}
  {% endfor %}

  <tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td><b>TOTAL VALUE</b></td>
    <td><b>${{ value }}</b></td>
  </tr>
</table>
{% endblock %}